# HTTP to HTTPS redirect
server {
    listen 80;
    server_name dr-smart.orcagroup.top  ;
    return 301 https://$host$request_uri;
}

# HTTPS server block
server {
    listen 443 ssl ;
    http2 on ;

    server_name dr-smart.orcagroup.top;

    # Service Worker
    location = /sw.js {
        alias /var/www/html/smart_healthcare_web/app/static/sw.js;
        add_header Service-Worker-Allowed /;
        add_header Content-Type application/javascript;
    }

    # PWA Manifest
    location = /manifest.json {
        alias /var/www/html/smart_healthcare_web/app/static/manifest.json;
        add_header Content-Type application/json;
    }

    # Static Files
    location /static/ {
        root /var/www/html/smart_healthcare_web/app;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Uploads
    location /uploads/ {
        alias /var/www/html/smart_healthcare_web/app/static/uploads/;
        expires 7d;
    }

    # Flask App via Gunicorn
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout 600s;
        proxy_send_timeout    600s;
        proxy_read_timeout    600s;
    }

    error_page 400 /errors/400.html;
    error_page 401 /errors/401.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;
    error_page 502 /errors/502.html;
    error_page 503 /errors/503.html;
    error_page 504 /errors/504.html;

    location ^~ /errors/ {
        root /var/www;
        internal;
    }

}
